remote_theme: tuur29/pages-themes-cayman
title: Tela Transeunte (Repositório)
description: Esta página tem como objetivo tornar disponível o código utilizado para o trabalho artístico Tela Transeunte.
show_downloads: false
darkmode: false
hide_first_title: false
logo_url: ./marcaHorizontalbranca.png
colors:
    gradient_left: "#A665DB"
    gradient_right: "#6AB6D2"
    header: "#fff"
    link: "#A665DB" # this default to gradient_color
    section_title: "#6AB6D2" # this default to gradient_color
